name: Test if engine Compiles

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   run: |
                    sudo apt update &&
                    sudo apt-get -y install cmake &&
                    sudo apt-get -y install freeglut3-dev &&
                    python3 build.py linux 




