name: Test if engine Compiles

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest] 

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install dependencies
                run: |
                    sudo apt update &&
                    sudo apt-get -y install cmake &&
                    sudo apt-get -y install g++-mingw-w64 && 
                    sudo apt-get -y install freeglut3-dev
                
            -   name: Test Compilation
                run: python3 build.py linux windows

            


